[package]
name = "notif_worker"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
dotenvy = "0.15.7"
lettre = "0.11.7"
lettre_email = "0.9.4"
r2d2 = "0.8.10"
r2d2_redis = "0.14.0"
redis = "0.26.0"
tokio = { version = "1.39.2", features = ["full"] }
