[package]
name = "api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.8.0"
env_logger = "0.11.4"
lazy_static = "1.5.0"
log = "0.4.22"
num_cpus = "1.16.0"
serde_json = "1.0.120"
